---
- name: test condition => true
  shell: echo "show shell command => is_true_condition"
  register: condition_true
  when: is_true_condition

- debug:
    msg: {{ condition_ture }}

- name: test condition => false
  shell: echo "show shell command => is_true_condition"
  register: condition_false
  when: !is_true_condition

- debug:
    msg: {{ condition_false }}