---
- debug:
    msg: "{{ group_var }}"
- debug:
     msg: "{{ host_var }}"
- debug:
    msg: "{{ play_book_var }}"
# - debug: msg= "abcccccccc"

- name: debug for a command message
  shell: echo 'Bibby Chung'
  register: username

- debug:
    msg: "{{ username }}"