---
# http://docs.ansible.com/ansible/apt_module.html
# http://docs.ansible.com/ansible/service_module.html

- name: apt-get update
  apt: 
    update_cache: yes

- name: Update the repository cache and update package "nginx" to latest version 
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Start the nginx
  service:
    name: nginx
    state: restarted

- name: Stop the nginx
  service:
    name: nginx
    state: stopped
